/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DlWeatherApp {
    }
}
declare global {
    interface HTMLDlWeatherAppElement extends Components.DlWeatherApp, HTMLStencilElement {
    }
    var HTMLDlWeatherAppElement: {
        prototype: HTMLDlWeatherAppElement;
        new (): HTMLDlWeatherAppElement;
    };
    interface HTMLElementTagNameMap {
        "dl-weather-app": HTMLDlWeatherAppElement;
    }
}
declare namespace LocalJSX {
    interface DlWeatherApp {
    }
    interface IntrinsicElements {
        "dl-weather-app": DlWeatherApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dl-weather-app": LocalJSX.DlWeatherApp & JSXBase.HTMLAttributes<HTMLDlWeatherAppElement>;
        }
    }
}
